### THE CONFIGURATION FOR EACH PHASE 

artifact_dir: artifacts 


## DATA INGESTION ## 
data_ingestion: 
  root_dir: RAG_TXT # where to get the ingestion (can use s3 bucket or blob storage later)
  path_name: "*/*.txt"
  artifact_path: artifacts/data_ingestion


## DATA TRANSFORMATION ## 
data_transformation: 
  source: artifacts/data_ingestion/RAG_TXT
  root_dir: MD_TRANSFORMED
  path_name: "*/*.md"
  artifact_path: artifacts/data_transformation
  llm: llama3.1-8b #google/gemma-4-31B-it:novita # using together.ai

## VECTOR DATABASE  
vector_db: 
  source: artifacts/data_transformation/MD_TRANSFORMED 
  path_name: "*/*.md"
  embedding_name: BAAI/bge-small-en-v1.5
  default_cluster_url: '1pqq36vrtl2hubhw7icxlw.c0.us-west3.gcp.weaviate.cloud' #NOTE: THIS IS TEMPORARY CLUSTER
  llm: llama3.1-8b #gemini-3.1-flash-lite-preview
  artifact_path: artifacts/vector_db/response/response.txt

## LLM (LARGE LANGUAGE MODELS) TO USE
llm: 
  groq: 
    oss120b: openai/gpt-oss-120b
    llama3_3: llama-3.3-70b-versatile
  gemini: 
      gemini3_1: gemini-3.1-flash-lite-preview



